### PR TITLE
fix: handle cases when no CI tasks are executed

### LINKED ISSUE #2: Error when no CI tasks ran
In some cases there are no CI tasks to run (no inputs changed), and this happens:

```
Error: ENOENT: no such file or directory, open '/home/runner/work/haohao.how/haohao.how/.moon/cache/ciReport.json'
    at async open (node:internal/fs/promises:636:25)
    at async readFile (node:internal/fs/promises:1246:14)
    at async readFileContent (file:///home/runner/work/_actions/appthrust/moon-ci-retrospect/v0/index.js:83:12)
    at async readCiReport (file:///home/runner/work/_actions/appthrust/moon-ci-retrospect/v0/index.js:35:26)
    at async main (file:///home/runner/work/_actions/appthrust/moon-ci-retrospect/v0/index.js:4:22)
    at async file:///home/runner/work/_actions/appthrust/moon-ci-retrospect/v0/index.js:126:5 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/runner/work/haohao.how/haohao.how/.moon/cache/ciReport.json'
}
```

### PR DESCRIPTION
**Pull request by suin**
Close #2

### CODE REVIEW

File: index.ts [hunk 1]
```diff
@@ -33,8 +37,11 @@ async function getWorkspaceRoot(): Promise<string> {
 	return process.cwd();
 }
 
-async function readCiReport(workspaceRoot: string): Promise<CiReport> {
+async function readCiReport(workspaceRoot: string): Promise<CiReport | undefined> {
 	const ciReportPath = `${workspaceRoot}/.moon/cache/ciReport.json`;
+	if (!(await fileExists(ciReportPath))) {
+		return;
+	}
```
Comment (suin) [inline index.ts:44]: This is the key part of the fix, handling cases where the CI report file doesn't exist or can't be read.
